# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaptionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=256)),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_maker.Caption')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=8)),
                ('reference_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('start_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('end_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='caption',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_maker.Media'),
        ),
    ]
