# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captionline',
            name='break_after',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caption',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='end_time',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='start_time',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
