# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 23:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caption_maker', '0005_auto_20160313_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caption',
            options={'ordering': ['label', 'order']},
        ),
        migrations.AddField(
            model_name='media',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
