# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0002_auto_20160219_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
